Update variable name to avoid InvalidArgumentError (index out of bounds) in the last exercise in lab 1.1
Rename variable from `matrix` to `images` to prevent the following error:
```
InvalidArgumentError: slice index 2 of dimension 1 out of bounds. [Op:StridedSlice] name: strided_slice/
```

For reference, matrix is defined two cells up with:
```
matrix = tf.constant([["Tennis", "No"], ["Basketball", "Yes"], ["Baseball", "No"]])
```
(which is a matrix of shape [3,2]) (a 2-d tensor)